- name: Create apex service
  hosts: dev2
  tasks:  
     - name: Deploy image to target registry docker service ls will be run
     
       command: 
          docker service ls
  
    
 
       
- name: Create apex service
  hosts: dev
  connection: local
  tasks:  
     - name: install from docker file 
       command: 
         docker stack deploy --compose-file docker-compose.yml vote 
