- name: Create apex service
  hosts: dev2
  connection: local
  tasks:  
     - name: Deploy image to target registry docker service ls will be run
     
       shell: >
          docker service ls  
  
    
 
       
- name: Create apex service
  hosts: dev
  connection: local
  tasks:  
     - name: install from docker file 
       shell: >
          docker stack deploy --compose-file docker-stack.yml sunny
        
       